version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout # clone source code
      - run: mkdir -p $TEST_RESULTS # create dir which store test result
      - restore_cache: # restore go modules
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Unit test
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname) # get all package name
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES # test all packages, export test result to gotestsum-report.xml
      - run:
          name: Build binary
          command: go build -o main
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results