version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: cat go.sum
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: unit test
          command: go test -v ./...
      - run:
          name: build bin
          command: go build -o main
      - run:
          name: diplay mods
          command: ls /go/pkg/mod/github.com
      - run: cat go.sum
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"